version: '3'

services:
  sortedLinkedList:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app

  composer:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
